spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
logging:
  file:
    # user.home是操作系统配置
    path: ${user.home}/logs/${spring.application.name}
  level:
    #mybatis 日志指向dao层
    com.gxl.springdemo.mapper: debug